### ISSUE TITLE
Can not build this project.

### ISSUE THREAD

**Issue by CrazyZfk** [digitalocean/ceph_exporter#72]
I download this project and flow below steps:
* cd ceph_exporter-master
* go get

 Here is the error:
```shell
./exporter.go:49: cannot use collectors.NewClusterUsageCollector(conn, cluster) (type *collectors.ClusterUsageCollector) as type "github.com/prometheus/client_golang/prometheus".Collector in array or slice literal:
	*collectors.ClusterUsageCollector does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/digitalocean/ceph_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)
./exporter.go:50: cannot use collectors.NewPoolUsageCollector(conn, cluster) (type *collectors.PoolUsageCollector) as type "github.com/prometheus/client_golang/prometheus".Collector in array or slice literal:
	*collectors.PoolUsageCollector does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/digitalocean/ceph_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)
./exporter.go:51: cannot use collectors.NewClusterHealthCollector(conn, cluster) (type *collectors.ClusterHealthCollector) as type "github.com/prometheus/client_golang/prometheus".Collector in array or slice literal:
	*collectors.ClusterHealthCollector does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/digitalocean/ceph_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)
./exporter.go:52: cannot use collectors.NewMonitorCollector(conn, cluster) (type *collectors.MonitorCollector) as type "github.com/prometheus/client_golang/prometheus".Collector in array or slice literal:
	*collectors.MonitorCollector does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/digitalocean/ceph_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)
./exporter.go:53: cannot use collectors.NewOSDCollector(conn, cluster) (type *collectors.OSDCollector) as type "github.com/prometheus/client_golang/prometheus".Collector in array or slice literal:
	*collectors.OSDCollector does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/digitalocean/ceph_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)
```

How I can fix it, Thank so much.

**Comment by wwalker** [comment]
for me the following works
    cd ceph_exporter
    make

**Comment by CrazyZfk** [comment]
It's not work for me.

Here is what happened:

```shell
[root@ceph ceph_exporter]# make
GO15VENDOREXPERIMENT=1 GOROOT=/usr/lib/golang /usr/lib/golang/bin/go build  -o ceph_exporter
# _/root/ceph_exporter
./exporter.go:49: cannot use collectors.NewClusterUsageCollector(conn, cluster) (type *collectors.ClusterUsageCollector) as type "github.com/prometheus/client_golang/prometheus".Collector in array or slice literal:
	*collectors.ClusterUsageCollector does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/digitalocean/ceph_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)
./exporter.go:50: cannot use collectors.NewPoolUsageCollector(conn, cluster) (type *collectors.PoolUsageCollector) as type "github.com/prometheus/client_golang/prometheus".Collector in array or slice literal:
	*collectors.PoolUsageCollector does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/digitalocean/ceph_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)
./exporter.go:51: cannot use collectors.NewClusterHealthCollector(conn, cluster) (type *collectors.ClusterHealthCollector) as type "github.com/prometheus/client_golang/prometheus".Collector in array or slice literal:
	*collectors.ClusterHealthCollector does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/digitalocean/ceph_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)
./exporter.go:52: cannot use collectors.NewMonitorCollector(conn, cluster) (type *collectors.MonitorCollector) as type "github.com/prometheus/client_golang/prometheus".Collector in array or slice literal:
	*collectors.MonitorCollector does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/digitalocean/ceph_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)
./exporter.go:53: cannot use collectors.NewOSDCollector(conn, cluster) (type *collectors.OSDCollector) as type "github.com/prometheus/client_golang/prometheus".Collector in array or slice literal:
	*collectors.OSDCollector does not implement "github.com/prometheus/client_golang/prometheus".Collector (wrong type for Collect method)
		have Collect(chan<- "github.com/digitalocean/ceph_exporter/vendor/github.com/prometheus/client_golang/prometheus".Metric)
		want Collect(chan<- "github.com/prometheus/client_golang/prometheus".Metric)
make: *** [ceph_exporter] Error 2

```

**Comment by cristicalin** [comment]
What version of golang are you using?
For us it works with golang 1.8 (Ubuntu 16.04 go packages from https://launchpad.net/~gophers/+archive/ubuntu/archive).

Here's a snippet from our docker build script:

```
export GOHOME=/usr/lib/go-1.8
export PATH=${GOHOME}/bin:${PATH}
export GOPATH=/go
export APPLOC=${GOPATH}/src/github.com/digitalocean
pushd ${APPLOC}
git clone https://github.com/digitalocean/ceph_exporter.git ceph_exporter
pushd ceph_exporter
go get -d .
go build -o /bin/ceph_exporter
```

**Comment by uncelvel** [comment]
So i have a issue with Grafana when using Prometheus. 
After pull and run Docker images Ceph-exporter then i have a result
https://i.imgur.com/HlLziT8.png
Add Data Sources to Grafana is OK too. 
![image](https://user-images.githubusercontent.com/13779596/32715071-36fd4380-c883-11e7-917d-c84efd9101c4.png)
But when i using Dash board https://grafana.com/dashboards/917 that failed to get 

![image](https://user-images.githubusercontent.com/13779596/32715228-fab1033e-c883-11e7-948e-e6978e8e3cf2.png)

So any suggestions for this issue?

**Comment by gtonello** [comment]
Hi guys,
I had the same issue here, trying to build ceph_exporter into CentOS 7.4, with golang 1.9.

Follow a snippet of what I did:
```
export GOPATH=$(pwd)
export PATH=$PATH:$GOPATH/bin
git clone https://github.com/digitalocean/ceph_exporter.git ceph_exporter
go get -d <each_package>
make
```
Errors output shows that you have prometheus in a different path that exporter.go is expecting. I only had to remove prometheus from `src/github.com/digitalocean/ceph_exporter/vendor/github.com/prometheus/client_golang/prometheus` and run make again.

**Comment by bastischubert** [comment]
Removing the whole vendor dir did the job for me (Fedora 27 and Ubuntu 16.04 )
```
git clone https://github.com/digitalocean/ceph_exporter.git ceph_exporter
cd ceph_exporter
# use the luminous branch
git checkout luminous
go get -d .
rm -rf $GOPATH/src/github.com/digitalocean/ceph_exporter/vendor/*
# use current go version:
perl -pni -e "s#1.5.3#1.10.1#g" Makefile.COMMON 
make
```

HTH

**Comment by sosodev** [comment]
Builds seem to be working fine with modern versions of Go :)
